### PR TITLE
log download on failure

### LINKED ISSUE #198: Provide reason when cloud deployment fails
When Azure template deploy fails, sunsone should at least provide reason of failed deployment.

### PR DESCRIPTION
**Pull request by laDok8**
automatically download all possible logs from azure on deployment failure.
resolves #198

### CODE REVIEW

File: azure/src/main/java/sunstone/azure/impl/AzureArmTemplateCloudDeploymentManager.java [hunk 1]
```diff
@@ -60,12 +64,35 @@ void deploy(String template, Map<String, String> parameters, String group, Strin
...
+                throw new RuntimeException(e);
+            }
+
+            PollResponse<?> pollResponse = acceptedDeployment.getSyncPoller().poll();
+            pollStatus = pollResponse.getStatus();
+        }
+        if (pollStatus != LongRunningOperationStatus.SUCCESSFULLY_COMPLETED) {
+            LOGGER.error("Azure deployment from template {} in \"{}\" group failed", deploymentName, group);
+            AzureUtils.downloadResourceGroupLogs(armManager, group);
+            undeploy(group);
```
Comment (istraka) [inline azure/src/main/java/sunstone/azure/impl/AzureArmTemplateCloudDeploymentManager.java:92]: Can the undeploy be controlled by a sunstone property? I have found it useful being able to investigate the resources after the deployment failed.

File: azure/src/main/java/sunstone/azure/impl/AzureUtils.java [hunk 2]
```diff
@@ -73,4 +80,40 @@ static Optional<Server> findAzurePgSqlServer(PostgreSqlManager pgsqlManager, Str
...
+
+    static void downloadResourceGroupLogs(AzureResourceManager armManager, String rgName) {
+        PagedIterable<EventData> x = armManager.activityLogs().defineQuery()
+                .startingFrom(OffsetDateTime.now().minusDays(1))
+                .endsBefore(OffsetDateTime.now())
+                .withAllPropertiesInResponse()
+                .filterByResourceGroup(rgName)
+                .execute();
+
+        try(java.io.FileWriter writer = new java.io.FileWriter(rgName + "-activity-log.log")) {
```
Comment (istraka) [inline azure/src/main/java/sunstone/azure/impl/AzureUtils.java:92]: This should be in `log` folder.

File: azure/src/main/java/sunstone/azure/impl/AzureUtils.java [hunk 3]
```diff
@@ -73,4 +80,40 @@ static Optional<Server> findAzurePgSqlServer(PostgreSqlManager pgsqlManager, Str
...
+                List<String> operations = d.deploymentOperations().list().stream().map(s ->  "\n" + s.timestamp() + ", state: " + s.provisioningState() + ", op: " + s.provisioningOperation() + ", resource: " + (s.targetResource() != null ? s.targetResource().resourceName() : "UNKNOWN_NAME") + ", type: " +  (s.targetResource() != null ? s.targetResource().resourceType() : "UNKNOWN_TYPE")).collect(Collectors.toList());
+                try {
+                    writer.write(d.error().getMessage());
+                    writer.write("\nError message: \n");
+                    writer.write(d.error().getDetails().stream().map(ManagementError::getMessage).collect(Collectors.joining()));
+                    writer.write("\nDeployment Info:\n");
+                    writer.write(d.name() + "\t" + d.provisioningState() + "\t" + d.timestamp() + "\twith:" + operations + "\n");
+                    writer.write("\n\n");
+                } catch (IOException e) {
+                    //ignore
```
Comment (istraka) [inline azure/src/main/java/sunstone/azure/impl/AzureUtils.java:111]: Can you log the exception?

File: azure/src/main/java/sunstone/azure/impl/AzureUtils.java [hunk 4]
```diff
@@ -73,4 +80,40 @@ static Optional<Server> findAzurePgSqlServer(PostgreSqlManager pgsqlManager, Str
...
+                .withAllPropertiesInResponse()
+                .filterByResourceGroup(rgName)
+                .execute();
+
+        try(java.io.FileWriter writer = new java.io.FileWriter(rgName + "-activity-log.log")) {
+            for (EventData e : x) {
+                writer.write(e.operationName().localizedValue() + "\tname: " + e.eventName().localizedValue() + "\tprops: " + e.properties() + "\tdesc: " + e.description() + "\ttimestamp: " + e.eventTimestamp() + "\tlevel: " + e.level() + "\n\n");
+            }
+        } catch (IOException e) {
+            //ignore
```
Comment (istraka) [inline azure/src/main/java/sunstone/azure/impl/AzureUtils.java:97]: Can you log the exception?

File: azure/src/main/java/sunstone/azure/impl/AzureArmTemplateCloudDeploymentManager.java [hunk 5]
```diff
@@ -60,12 +64,35 @@ void deploy(String template, Map<String, String> parameters, String group, Strin
...
+        Accepted<Deployment> acceptedDeployment = armManager.deployments().define(deploymentName)
                 .withExistingResourceGroup(group)
                 .withTemplate(template)
                 .withParameters(parametersFromMap(template, parameters))
                 .withMode(DeploymentMode.INCREMENTAL)
-                .create();
+                .beginCreate();
+
+        // polling wait
+        final Duration pollInterval = Duration.ofSeconds(10);
```
Comment (istraka) [inline azure/src/main/java/sunstone/azure/impl/AzureArmTemplateCloudDeploymentManager.java:76]: Where did the 10 seconds come from? Isn't it too much? Moreover, it is a magic constant. Can it be configured via sunstone property?

**Review by istraka — CHANGES_REQUESTED** [review]

File: azure/src/main/java/sunstone/azure/impl/AzureArmTemplateCloudDeploymentManager.java (hunk 5 above)
Comment (laDok8) [reply azure/src/main/java/sunstone/azure/impl/AzureArmTemplateCloudDeploymentManager.java:76]: 10 sec was just my first estimate, it may not be enough for long files/ slow connection ... or contrary too much, so property it is :+1:

File: azure/src/main/java/sunstone/azure/impl/AzureArmTemplateCloudDeploymentManager.java (hunk 1 above)
Comment (laDok8) [reply azure/src/main/java/sunstone/azure/impl/AzureArmTemplateCloudDeploymentManager.java:95]: I would tackle this in separate PR changing undeploy(..) logic for #201

**Review by istraka — APPROVED** [review]
